on: [pull_request]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Asana Github Action Run
    steps:
      - name: Getting the Action
        id: asana-github
        uses: actions/hello-world-docker-action@v1
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"